### get all movies
GET http://localhost:8004/api/movies

### get movie by id
GET http://localhost:8004/api/movies/1

### delete movie by id
DELETE http://localhost:8004/api/movies/5
Authorization: Bearer <YOUR_TOKEN>

### search movie
GET http://localhost:8004/api/movies/search?q=mul

### add new or update by id existing movie (0 - add, 1:inf - update by id
POST http://localhost:8004/api/movies
Authorization: Bearer <YOUR_TOKEN>
Content-Type: application/json

{
  "id": 0,
  "title": "",
  "description": "",
  "image": "",
  "year": "",
  "country": "",
  "actors": [
    ""
  ],
  "genres": [
    ""
  ],
  "creators": [
    ""
  ],
  "studio": "",
  "ext_link": ""
}

###